language: php
php:
  - '7.1'
services:
  - docker
before_script:
  - docker-compose up -d --build
  - docker exec application ./vendor/bin/simple-phpunit
script:
  - docker exec application ./vendor/bin/simple-phpunit
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
notifications:
    on_success: never
    on_failure: always